name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Compile main.cpp
        run: g++ main.cpp -o main.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: main.exe
