name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW via Chocolatey
        run: choco install mingw -y

      - name: Add MinGW to PATH
        run: |
          echo "C:\ProgramData\mingw64\mingw64\bin" >> $env:GITHUB_PATH

      - name: Compile main.cpp
        run: g++ main.cpp -o main.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: main.exe
